.TH "C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/autonmousDrive.py" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/autonmousDrive.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpy\-scripts\&.autonmousDrive\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.enableA\fP = 36"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.enableB\fP = 32"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.port1\fP = 40"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.port2\fP = 38"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.port3\fP = 35"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.port4\fP = 37"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.lampA\fP = 33"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.lampB\fP = 31"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.GPIO_TRIGGER\fP = 16"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.GPIO_ECHO\fP = 18"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.autonmousDrive\&.distance_forward\fP = 10"
.br
.ti -1c
.RI "\fBpy\-scripts\&.autonmousDrive\&.piTank\fP = PiTank(enableA, enableB, 100, port1, port2, port3, port4)"
.br
.RI "\fISetup\fP############################################################### "
.ti -1c
.RI "\fBpy\-scripts\&.autonmousDrive\&.distance\fP = int(lib_distance\&.measure_average_of_3(GPIO_TRIGGER, GPIO_ECHO))"
.br
.RI "_Start_of_Main######################################################### "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
