.TH "C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/Index.php" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/Index.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$state\fP = 'Mark 1 is ready'"
.br
.ti -1c
.RI "if(isset( $_REQUEST['RPS1'])) if(isset( $_REQUEST['RPS2'])) if(isset( $_REQUEST['RPS3'])) if(isset( $_REQUEST['RPS4'])) if(isset( $_REQUEST['RPS5'])) if(isset( $_REQUEST['RPS6'])) \fBif\fP (isset($_REQUEST[ 'RPS7']))"
.br
.ti -1c
.RI "\fB$datetime\fP = date('Y/m/d') + ' ' + date('h:i:sa')"
.br
.ti -1c
.RI "\fB$License\fP = ' '"
.br
.ti -1c
.RI "\fB$content\fP = 'Lizens ausgestellt am $datetime'"
.br
.ti -1c
.RI "if(isset( $_REQUEST['Modul1'])) if(isset( $_REQUEST['Modul2'])) if(isset( $_REQUEST['Modul1_OFF'])) \fBif\fP (isset($_REQUEST[ 'Modul2_OFF']))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$content = 'Lizens ausgestellt am $datetime'"

.SS "$datetime = date('Y/m/d') + ' ' + date('h:i:sa')"

.SS "$License = ' '"

.SS "$state = 'Mark 1 is ready'"

.SS "if (isset($_REQUEST[ 'Modul1'])) if (isset($_REQUEST[ 'Modul2'])) if (isset($_REQUEST[ 'Modul1_OFF'])) if(isset( $_REQUEST['Modul2_OFF']))"

.SS "if (isset($_REQUEST[ 'RPS1'])) if (isset($_REQUEST[ 'RPS2'])) if (isset($_REQUEST[ 'RPS3'])) if (isset($_REQUEST[ 'RPS4'])) if (isset($_REQUEST[ 'RPS5'])) if (isset($_REQUEST[ 'RPS6'])) if(isset( $_REQUEST['RPS7']))"

.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
