.TH "C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/myLib/lib_distance.py" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/myLib/lib_distance.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpy\-scripts\&.myLib\&.lib_distance\fP"
.br
.ti -1c
.RI " \fBLibraries\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.lib_distance\&.simple_measure\fP (GPIO_TRIGGER, GPIO_ECHO)"
.br
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.lib_distance\&.measure_average_of_3\fP (GPIO_TRIGGER, GPIO_ECHO)"
.br
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.lib_distance\&.measure_average_of_x\fP (x, GPIO_TRIGGER, GPIO_ECHO)"
.br
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.lib_distance\&.printSettings\fP ()"
.br
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.lib_distance\&.print_formattedMeasure\fP (GPIO_TRIGGER, GPIO_ECHO)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.lib_distance\&.temperature\fP = 20"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.lib_distance\&.speedSound\fP = 33100 + (0\&.6 * temperature)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
