.TH "C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/myLib/lib_HTTP_Interface.py" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/myLib/lib_HTTP_Interface.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpy\-scripts\&.myLib\&.lib_HTTP_Interface\fP"
.br
.ti -1c
.RI " \fBLibraries\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.lib_HTTP_Interface\&.request\fP ()"
.br
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.lib_HTTP_Interface\&.check_payment\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
