.TH "main.py-scripts.myLib.lib_movement" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py-scripts.myLib.lib_movement
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwheel_left_FORWARD\fP (\fBlampA\fP, \fBport3\fP, \fBport4\fP)"
.br
.ti -1c
.RI "def \fBwheel_left_BACKWARD\fP (\fBlampA\fP, \fBport3\fP, \fBport4\fP)"
.br
.ti -1c
.RI "def \fBwheel_right_FORWARD\fP (\fBlampB\fP, \fBport1\fP, \fBport2\fP)"
.br
.ti -1c
.RI "def \fBwheel_right_BACKWARD\fP (\fBlampB\fP, \fBport1\fP, \fBport2\fP)"
.br
.ti -1c
.RI "def \fBclean\fP (\fBlampA\fP, \fBport1\fP, \fBport2\fP, \fBlampB\fP, \fBport3\fP, \fBport4\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def main\&.py\-scripts\&.myLib\&.lib_movement\&.clean ( lampA,  port1,  port2,  lampB,  port3,  port4)"

.SS "def main\&.py\-scripts\&.myLib\&.lib_movement\&.wheel_left_BACKWARD ( lampA,  port3,  port4)"

.SS "def main\&.py\-scripts\&.myLib\&.lib_movement\&.wheel_left_FORWARD ( lampA,  port3,  port4)"

.SS "def main\&.py\-scripts\&.myLib\&.lib_movement\&.wheel_right_BACKWARD ( lampB,  port1,  port2)"

.SS "def main\&.py\-scripts\&.myLib\&.lib_movement\&.wheel_right_FORWARD ( lampB,  port1,  port2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
