.TH "main.py-scripts.myLib.Motortest" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py-scripts.myLib.Motortest
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.RI "usecases########################## "
.ti -1c
.RI "def \fBprintPin\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBenableA\fP = 36"
.br
.ti -1c
.RI "int \fBport1\fP = 40"
.br
.ti -1c
.RI "int \fBport2\fP = 38"
.br
.ti -1c
.RI "int \fBport3\fP = 35"
.br
.ti -1c
.RI "int \fBport4\fP = 37"
.br
.ti -1c
.RI "int \fBenableB\fP = 32"
.br
.ti -1c
.RI "\fBmotor1GPIO\fP = GPIO\&.PWM(\fBenableA\fP, 100)"
.br
.ti -1c
.RI "\fBmotor2GPIO\fP = GPIO\&.PWM(\fBenableB\fP, 100)"
.br
.ti -1c
.RI "int \fBdc\fP = 70"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def main\&.py\-scripts\&.myLib\&.Motortest\&.main ()"

.PP
usecases########################## 
.SS "def main\&.py\-scripts\&.myLib\&.Motortest\&.printPin ()"

.SH "Variable Documentation"
.PP 
.SS "int main\&.py\-scripts\&.myLib\&.Motortest\&.dc = 70"

.SS "int main\&.py\-scripts\&.myLib\&.Motortest\&.enableA = 36"

.SS "int main\&.py\-scripts\&.myLib\&.Motortest\&.enableB = 32"

.SS "main\&.py\-scripts\&.myLib\&.Motortest\&.motor1GPIO = GPIO\&.PWM(\fBenableA\fP, 100)"

.SS "main\&.py\-scripts\&.myLib\&.Motortest\&.motor2GPIO = GPIO\&.PWM(\fBenableB\fP, 100)"

.SS "int main\&.py\-scripts\&.myLib\&.Motortest\&.port1 = 40"

.SS "int main\&.py\-scripts\&.myLib\&.Motortest\&.port2 = 38"

.SS "int main\&.py\-scripts\&.myLib\&.Motortest\&.port3 = 35"

.SS "int main\&.py\-scripts\&.myLib\&.Motortest\&.port4 = 37"

.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
