.TH "main.py-scripts.myLib.lib_datawork" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py-scripts.myLib.lib_datawork
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBopenAndRead\fP (\fBdataname\fP)"
.br
.ti -1c
.RI "def \fBopenAndWrite\fP (\fBdataname\fP, text)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBdataname\fP = '\&.\&./test\&.txt'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def main\&.py\-scripts\&.myLib\&.lib_datawork\&.openAndRead ( dataname)"

.PP
.nf
Documentation for method.
openAndRead(string:dateiname)
öffnet Datei und liest ihren Inhalt ein. Dieser wird im return-Wert lines zurückgegeben.
.fi
.PP
 
.SS "def main\&.py\-scripts\&.myLib\&.lib_datawork\&.openAndWrite ( dataname,  text)"

.PP
.nf
Documentation for method.
openAndWrite(string:dateiname, string:text)
öffnet Datei und liest ihren Inhalt ein. Dieser wird im return-Wert lines zurückgegeben.
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "string main\&.py\-scripts\&.myLib\&.lib_datawork\&.dataname = '\&.\&./test\&.txt'"

.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
