.TH "main.py" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
-scripts::myLib::lib_datawork
.PP
.nf
"@package docstring
Documentation for this module.

Zweck: Interaktion mit .txt-Files
Inhalt: Methoden:   openAndRead(string:Dateiname)
                 openAndWrite(string:Dateiname, string:text)

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
