.TH "md__c_1__users_eising__desktop_git2_2_pydrone__p_y_drone__r_e_a_d_m_e" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users_eising__desktop_git2_2_pydrone__p_y_drone__r_e_a_d_m_e \- PYDrone 
Repository for Pydrone Project, running on RPI, coded in Python Author : TinkerPal99 Start of project on github: 12\&.10\&.2019 Contributors:
.PP
\fB\fISummary\fP\fP
.IP "1." 4
First things First
.IP "2." 4
Preparation
.IP "3." 4
Important informations
.PP
.PP
\fBFirst things First\fP This is a control-software, build to control different Drones, Rovers and things alike\&. The blue-prints for these devices aren't online now and probably never will\&.
.PP
The actual \fBinit\fP can be found in main/py-scripts The webinterface can be found in main, called \fBIndex\&.php\fP
.PP
\fBPreparation\fP For using the webinterface you need a php-runner\&.
.PP
\fBImportant informations\fP
.PP
In the moment I am trying to rrebuild the whole system oop, first try can be found in main/py-scripts/PiTank\&.py and autonomousDrive\&.py 
