.TH "C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/archiv/Motor-H1.py" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/archiv/Motor-H1.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMotor\-H1\fP"
.br
.ti -1c
.RI " \fBarchive\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBMotor\-H1\&.enable\fP (en)"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.disable\fP (en)"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.wheelleft_FORWARD\fP ()"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.wheelleft_BACKWARD\fP ()"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.wheelright_FORWARD\fP ()"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.wheelright_BACKWARD\fP ()"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.speed\fP ()"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.clean\fP ()"
.br
.ti -1c
.RI "def \fBMotor\-H1\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBMotor\-H1\&.speed\fP = 0"
.br
.ti -1c
.RI "string \fBMotor\-H1\&.en\fP = 'null'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
