.TH "C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/myLib/Motortest.py" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/myLib/Motortest.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpy\-scripts\&.myLib\&.Motortest\fP"
.br
.ti -1c
.RI " \fBLibraries\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.Motortest\&.main\fP ()"
.br
.RI "usecases########################## "
.ti -1c
.RI "def \fBpy\-scripts\&.myLib\&.Motortest\&.printPin\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.Motortest\&.enableA\fP = 36"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.Motortest\&.port1\fP = 40"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.Motortest\&.port2\fP = 38"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.Motortest\&.port3\fP = 35"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.Motortest\&.port4\fP = 37"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.Motortest\&.enableB\fP = 32"
.br
.ti -1c
.RI "\fBpy\-scripts\&.myLib\&.Motortest\&.motor1GPIO\fP = GPIO\&.PWM(enableA, 100)"
.br
.ti -1c
.RI "\fBpy\-scripts\&.myLib\&.Motortest\&.motor2GPIO\fP = GPIO\&.PWM(enableB, 100)"
.br
.ti -1c
.RI "int \fBpy\-scripts\&.myLib\&.Motortest\&.dc\fP = 70"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
