.TH "py-scripts.myLib.lib_rgb" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
py-scripts.myLib.lib_rgb
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBclean\fP ()"
.br
.ti -1c
.RI "def \fBlight\fP ()"
.br
.ti -1c
.RI "def \fBblink_left\fP ()"
.br
.ti -1c
.RI "def \fBblink_right\fP ()"
.br
.ti -1c
.RI "def \fBbl\fP (y)"
.br
.ti -1c
.RI "def \fBbr\fP (y)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBf\fP = open('\&.\&./test\&.txt', 'r')"
.br
.ti -1c
.RI "\fBlines\fP = f\&.readlines()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def py\-scripts\&.myLib\&.lib_rgb\&.bl ( y)"

.SS "def py\-scripts\&.myLib\&.lib_rgb\&.blink_left ()"

.SS "def py\-scripts\&.myLib\&.lib_rgb\&.blink_right ()"

.SS "def py\-scripts\&.myLib\&.lib_rgb\&.br ( y)"

.SS "def py\-scripts\&.myLib\&.lib_rgb\&.clean ()"

.SS "def py\-scripts\&.myLib\&.lib_rgb\&.light ()"

.SH "Variable Documentation"
.PP 
.SS "py\-scripts\&.myLib\&.lib_rgb\&.f = open('\&.\&./test\&.txt', 'r')"

.SS "py\-scripts\&.myLib\&.lib_rgb\&.lines = f\&.readlines()"

.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
