.TH "py-scripts.myLib.PiTank" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
py-scripts.myLib.PiTank
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPiTank\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
