.TH "py-scripts.myLib.license" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
py-scripts.myLib.license
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBcounter\fP = 0"
.br
.ti -1c
.RI "string \fBa\fP = '\&.\&./Lizenzen/'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string py\-scripts\&.myLib\&.license\&.a = '\&.\&./Lizenzen/'"

.SS "int py\-scripts\&.myLib\&.license\&.counter = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
