.TH "py-scripts.myLib.lib_datawork" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
py-scripts.myLib.lib_datawork
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBopenAndRead\fP (\fBdataname\fP)"
.br
.RI "Documentation for method\&. "
.ti -1c
.RI "def \fBopenAndWrite\fP (\fBdataname\fP, text)"
.br
.RI "Documentation for method\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBdataname\fP = '\&.\&./test\&.txt'"
.br
.RI "Documentation for a variable\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "def py\-scripts\&.myLib\&.lib_datawork\&.openAndRead ( dataname)"

.PP
Documentation for method\&. openAndRead(string:dateiname)
.PP
öffnet Datei und liest ihren Inhalt ein\&. Dieser wird im return-Wert \fIlines\fP zurückgegeben\&. 
.SS "def py\-scripts\&.myLib\&.lib_datawork\&.openAndWrite ( dataname,  text)"

.PP
Documentation for method\&. openAndWrite(string:dateiname, string:text)
.PP
öffnet Datei und liest ihren Inhalt ein\&. Dieser wird im return-Wert lines zurückgegeben\&.''" 
.SH "Variable Documentation"
.PP 
.SS "string py\-scripts\&.myLib\&.lib_datawork\&.dataname = '\&.\&./test\&.txt'"

.PP
Documentation for a variable\&. Diese Variable dient als default für eine angesprochene Datei\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
