.TH "pyexample" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyexample
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Documentation for this module\&.
.PP
Zweck: Interaktion mit \&.txt-Files Inhalt: Methoden: openAndRead(string:Dateiname) openAndWrite(string:Dateiname, string:text) 
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
