.TH "C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/archiv/sonic_sense.py" 3 "Tue Oct 22 2019" "Version 1.0" "PyDrone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/eising/Desktop/git2_2/pydrone/PYDrone/piTank/main/py-scripts/archiv/sonic_sense.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsonic_sense\fP"
.br
.ti -1c
.RI " \fBarchive\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsonic_sense\&.measure\fP ()"
.br
.ti -1c
.RI "def \fBsonic_sense\&.measure_average\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBsonic_sense\&.GPIO_TRIGGER\fP = 16"
.br
.ti -1c
.RI "int \fBsonic_sense\&.GPIO_ECHO\fP = 18"
.br
.ti -1c
.RI "int \fBsonic_sense\&.temperature\fP = 20"
.br
.ti -1c
.RI "int \fBsonic_sense\&.speedSound\fP = 33100 + (0\&.6 * temperature)"
.br
.ti -1c
.RI "def \fBsonic_sense\&.distance\fP = measure_average()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PyDrone from the source code\&.
